# Generated by Django 3.0.13 on 2021-02-23 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inByulGram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(upload_to='inByulGram/post/%Y/%m/%d'),
        ),
    ]
