# Generated by Django 3.0.13 on 2021-02-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inByulGram', '0002_auto_20210223_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(default='서울', max_length=100),
        ),
    ]
